spring.application.name=DataFood_BackEnd

spring.datasource.url=jdbc:sqlserver://LAPTOP-H4V75VLP;databaseName=DataFood;encrypt=false;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true